language: cpp
dist: xenial
sudo: false
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
    - libgl1-mesa-dev
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev

before_script:
- git clone https://github.com/sfml/sfml
- cd SFML
- git checkout 2f11710abc5aa478503a7ff3f9e654bd2078ebab
- mkdir build && cd build
- cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install
- cmake --build . --target install
- cd ../..

script:
- export CC=gcc-7
- export CXX=g++-7
- gcc -v
- g++ -v
- cmake --version
- mkdir build && cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DSFML_DIR=$TRAVIS_BUILD_DIR/sfml/install/lib/cmake/SFML -DCMAKE_INSTALL_PREFIX=../install
- cmake --build . --config Release -- -j ${nproc}

branches:
  only:
  - develop

notifications:
  email:
  - dreqn1te@gmail.com
